name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          # build(master): release 1.2.3
          pull-request-title-pattern: 'build${scope}: release${component} ${version}'
          extra-files: |
            README.md
            docs/getting-started.md

      - name: Echo release outputs
        if: ${{ steps.release.outputs }}
        run: echo '${{ toJson(steps.release) }}'
        continue-on-error: true

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.pr }}
        with:
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      - name: Configure Git user
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git --no-pager show --name-only

      - name: Run CHANGELOG.md through Prettier
        if: ${{ steps.release.outputs.pr }}
        run: npx prettier --write CHANGELOG.md

      - name: Commit and push
        if: ${{ steps.release.outputs.pr }}
        run: |
          git add CHANGELOG.md
          git commit -m 'chore: run CHANGELOG.md through Prettier' --no-verify
          git push
